/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-container-low": "#fff1ed",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#f0dfdb",
        "tertiary-fixed-dim": "#f6be39",
        "on-secondary-container": "#11278e",
        "inverse-surface": "#382e2c",
        "surface-dim": "#e7d6d3",
        primary: "#94442e",
        "on-background": "#221a17",
        "inverse-primary": "#ffb5a1",
        "on-primary-fixed-variant": "#79301b",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-container": "#8596ff",
        "primary-fixed": "#ffdbd1",
        "surface-variant": "#f0dfdb",
        secondary: "#4355b9",
        "on-secondary-fixed-variant": "#293ca0",
        "on-primary-container": "#fffcff",
        "primary-fixed-dim": "#ffb5a1",
        "secondary-fixed-dim": "#bac3ff",
        "tertiary-container": "#956e00",
        "surface-container": "#fbeae6",
        "on-primary-fixed": "#3b0900",
        "surface-bright": "#fff8f6",
        "on-primary": "#ffffff",
        "surface-tint": "#974730",
        background: "#fff8f6",
        "surface-container-high": "#f5e5e0",
        tertiary: "#765700",
        "on-secondary-fixed": "#00105c",
        "outline-variant": "#dbc1ba",
        "primary-container": "#b35c44",
        "on-tertiary-container": "#fffbff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#feede9",
        "tertiary-fixed": "#ffdfa0",
        "secondary-fixed": "#dee0ff",
        error: "#ba1a1a",
        surface: "#fff8f6",
        outline: "#88726d",
        "on-surface": "#221a17",
        "on-tertiary-fixed": "#261a00",
        "on-surface-variant": "#55433e",
        "on-tertiary-fixed-variant": "#5c4300",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "4px",
        "margin-desktop": "40px",
        "container-max": "1440px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "label-sm": ["Inter"],
        "mono-data": ["Courier Prime"],
        "title-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "mono-data": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
